
# Inherit from msm8974
-include device/qcom/msm8974/BoardConfig.mk

DEVICE_PATH := device/sharp/PA23

# Assert
TARGET_OTA_ASSERT_DEVICE := PA23,SBM303SH

# Boot images
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom user_debug=23 msm_rtb.filter=0x3b7 ehci-hcd.park=3 androidboot.bootdevice=msm_sdcc.1
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_SEPARATED_DT := true
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000 --tags_offset 0x01e00000
#BOARD_MKBOOTIMG_ARGS += --dt $(PRODUCT_OUT)/obj/KERNEL_OBJ/arch/arm/boot/msm8974-sharp-pa23-v2.2.dtb

# Bootloader
TARGET_NO_BOOTLOADER := true

# Kernel
#TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x01100000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x01900000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x80000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x80000000

# Properties
#TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Radio
ADD_RADIO_FILES := false

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.qcom
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
DEVICE_RESOLUTION := 720x1280
RECOVERY_GRAPHICS_USE_LINELENGTH := true
#TW_EXCLUDE_MTP := true
TW_EXCLUDE_SUPERSU := true
TW_NO_USB_STORAGE := true
TW_NO_REBOOT_BOOTLOADER := true

# WIFI
BOARD_HAS_QCOM_WLAN := true

